#!/usr/bin/env bash
set -eu

echo "Starting CoinDrafts Linera Application..."

# Create .env if it doesn't exist
if [ ! -f /build/.env ]; then
    echo "Creating .env from .env.example..."
    cp /build/.env.example /build/.env
fi

# Set up Linera network
eval "$(linera net helper)"
linera_spawn linera net up --with-faucet

export LINERA_FAUCET_URL=http://localhost:8080
linera wallet init --faucet="$LINERA_FAUCET_URL"
linera wallet request-chain --faucet="$LINERA_FAUCET_URL"

# Build all applications
echo "Building applications..."
cd /build
cargo build --release --target wasm32-unknown-unknown --package coindrafts-core --package traditional-leagues --package price-prediction

# Deploy CoinDrafts Core
echo "Deploying CoinDrafts Core..."
CORE_OUTPUT=$(linera publish-and-create target/wasm32-unknown-unknown/release/coindrafts_core_{contract,service}.wasm --json-argument "null" 2>&1)
COINDRAFTS_CORE_APP_ID=$(echo "$CORE_OUTPUT" | grep -o '[a-f0-9]\{64\}' | tail -1)
echo "Core App ID: $COINDRAFTS_CORE_APP_ID"
echo "Syncing Core app..."
linera sync

# Deploy Traditional Leagues
echo "Deploying Traditional Leagues..."
LEAGUES_OUTPUT=$(linera publish-and-create target/wasm32-unknown-unknown/release/traditional_leagues_{contract,service}.wasm --json-argument "null" 2>&1)
TRADITIONAL_LEAGUES_APP_ID=$(echo "$LEAGUES_OUTPUT" | grep -o '[a-f0-9]\{64\}' | tail -1)
echo "Leagues App ID: $TRADITIONAL_LEAGUES_APP_ID"
echo "Syncing Leagues app..."
linera sync

# Deploy Price Prediction
echo "Deploying Price Prediction..."
PREDICTION_OUTPUT=$(linera publish-and-create target/wasm32-unknown-unknown/release/price_prediction_{contract,service}.wasm --json-argument "null" 2>&1)
PRICE_PREDICTION_APP_ID=$(echo "$PREDICTION_OUTPUT" | grep -o '[a-f0-9]\{64\}' | tail -1)
echo "Price Prediction App ID: $PRICE_PREDICTION_APP_ID"
echo "Syncing Prediction app..."
linera sync

# Get default chain ID and admin chain ID
DEFAULT_CHAIN_ID=$(linera wallet show 2>&1 | grep -o '[a-f0-9]\{64,66\}' | sed -n '2p')
ADMIN_CHAIN_ID=$(linera wallet show 2>&1 | grep -o '[a-f0-9]\{64,66\}' | sed -n '1p')
DEFAULT_OWNER=$(linera wallet show 2>&1 | grep -E "Owner" | grep -o '[a-f0-9]\{64\}' | head -1)
echo "Chain ID: $DEFAULT_CHAIN_ID"
echo "Admin Chain ID: $ADMIN_CHAIN_ID"
echo "Default Owner: $DEFAULT_OWNER"

# Sync the chain before starting service (while no locks are held)
echo "Synchronizing chain state..."
linera sync

# Wait for blob synchronization
echo "Waiting for blob synchronization..."
sleep 30

# Start GraphQL service
echo "Starting GraphQL service..."
linera service --port 8081 > /tmp/graphql-service.log 2>&1 &
echo "Waiting for GraphQL service to start..."
sleep 5

echo ""
echo "Testing tournament functionality..."
echo ""

# Test 1: Create a tournament
echo "🏆 Creating tournament..."
CREATE_RESULT=$(curl -s -X POST "http://localhost:8081/chains/$DEFAULT_CHAIN_ID/applications/$TRADITIONAL_LEAGUES_APP_ID" \
  -H "Content-Type: application/json" \
  -d '{"query":"mutation { createTournament(name: \"Test Tournament\", entryFeeUsdc: \"10\", maxParticipants: 8, tournamentType: SINGLE_ELIMINATION, category: \"L1_CHAINS\") }"}')
echo "Create result: $CREATE_RESULT"
echo ""

# Test 2: Read tournaments  
echo "📋 Reading tournaments..."
READ_RESULT=$(curl -s -X POST "http://localhost:8081/chains/$DEFAULT_CHAIN_ID/applications/$TRADITIONAL_LEAGUES_APP_ID" \
  -H "Content-Type: application/json" \
  -d '{"query":"{ tournaments { id name status maxParticipants currentParticipants category } }"}')
echo "Read result: $READ_RESULT"
echo ""
echo "✅ Tournament tests completed!"
echo ""

# Setup frontend environment
cd /build/frontend

# Write .env file with admin chain for reliable GraphQL access
cat > .env << EOF
# Auto-generated by run.bash deployment - DO NOT EDIT MANUALLY
PUBLIC_DEFAULT_CHAIN_ID=$DEFAULT_CHAIN_ID
PUBLIC_ADMIN_CHAIN_ID=$ADMIN_CHAIN_ID
PUBLIC_COINDRAFTS_CORE_APP_ID=$COINDRAFTS_CORE_APP_ID
PUBLIC_TRADITIONAL_LEAGUES_APP_ID=$TRADITIONAL_LEAGUES_APP_ID
PUBLIC_PRICE_PREDICTION_APP_ID=$PRICE_PREDICTION_APP_ID
PUBLIC_DEFAULT_OWNER=$DEFAULT_OWNER

# Reown AppKit Configuration (if needed for production)
VITE_REOWN_PROJECT_ID=your-project-id-here
EOF

echo "✅ Frontend environment configured with admin chain"

# Setup Node.js environment and install frontend dependencies
echo "Setting up Node.js and installing frontend dependencies..."
cd /build/frontend
. ~/.nvm/nvm.sh
nvm use lts/krypton
npm install
cd /build

# Run auto-seed script
echo ""
echo "🌱 Running auto-seed script..."
node seed-data.js

echo ""
echo "🎮 Pre-seeding leaderboard..."
node scripts/preseed-leaderboard.js

echo ""
echo "===== DEPLOYMENT COMPLETE ====="
echo "Core: $COINDRAFTS_CORE_APP_ID"
echo "Prediction: $PRICE_PREDICTION_APP_ID"
echo "Leagues: $TRADITIONAL_LEAGUES_APP_ID"
echo "Chain: $DEFAULT_CHAIN_ID"
echo "Admin Chain: $ADMIN_CHAIN_ID"
echo "GraphQL: http://localhost:8081"
echo "==============================="
echo ""
echo "GraphQL service is running. Test with:"
echo "curl -X POST http://localhost:8081 -H 'Content-Type: application/json' -d '{\"query\":\"{ __schema { types { name } } }\"}'"
echo ""

# Start frontend development server
echo "🚀 Starting frontend development server..."
cd /build/frontend
. ~/.nvm/nvm.sh
nvm use lts/krypton
npm run dev -- --host 0.0.0.0 --port 5173 &

echo ""
echo "🎉 EVERYTHING IS RUNNING!"
echo "Frontend: http://localhost:5173"
echo "GraphQL: http://localhost:8081"
echo ""

# Keep container running
tail -f /tmp/graphql-service.log